# Generated by Django 5.1.5 on 2025-02-10 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_auction_bid_comments_listings"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="closed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="auction",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="bid",
            name="auction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="auctions.auction"
            ),
        ),
        migrations.AlterField(
            model_name="bid",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="comments",
            name="auction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="auctions.auction"
            ),
        ),
        migrations.AlterField(
            model_name="comments",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
