# Generated by Django 5.1.5 on 2025-02-10 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_auction_closed_alter_auction_seller_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Listings",
            new_name="Listing",
        ),
    ]
