# Generated by Django 5.1.5 on 2025-02-28 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0006_category_watchlist_listing_seller_listing_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="watchlist",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="watchlistuser",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="bid",
            name="auction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="auctions.listing"
            ),
        ),
        migrations.AlterField(
            model_name="comments",
            name="auction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="auctions.listing"
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="image_url",
            field=models.URLField(blank=True, max_length=4000, null=True),
        ),
    ]
