# Generated by Django 5.1.5 on 2025-03-02 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0007_listing_watchlist_alter_bid_auction_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comments",
            old_name="auction",
            new_name="listing",
        ),
    ]
