# Generated by Django 5.1.5 on 2025-03-08 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0008_rename_auction_comments_listing"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comments",
            name="date",
        ),
        migrations.AlterField(
            model_name="comments",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listingscomment",
                to="auctions.listing",
            ),
        ),
        migrations.AlterField(
            model_name="comments",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="userscommnet",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
