# Generated by Django 5.1.5 on 2025-03-09 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0012_alter_listing_starting_bid_bid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bid",
            name="auction",
        ),
        migrations.RemoveField(
            model_name="bid",
            name="bid_date",
        ),
        migrations.AlterField(
            model_name="bid",
            name="bid_price",
            field=models.DecimalField(decimal_places=2, default="0", max_digits=10),
        ),
        migrations.AlterField(
            model_name="listing",
            name="starting_bid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bid",
                to="auctions.bid",
            ),
        ),
    ]
