# Generated by Django 5.1.5 on 2025-03-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0013_remove_bid_auction_remove_bid_bid_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="current_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
