# Generated by Django 5.1.5 on 2025-03-09 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0014_listing_current_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="current_price",
            field=models.DecimalField(
                decimal_places=2,
                default=models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="bid",
                    to="auctions.bid",
                ),
                max_digits=10,
            ),
        ),
    ]
