# Generated by Django 5.1.5 on 2025-03-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0015_alter_listing_current_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="current_price",
            field=models.DecimalField(
                decimal_places=2, default="starting_bid", max_digits=10
            ),
        ),
    ]
