# Generated by Django 5.1.5 on 2025-03-09 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0016_alter_listing_current_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auction",
            name="seller",
        ),
        migrations.DeleteModel(
            name="Watchlist",
        ),
        migrations.DeleteModel(
            name="auction",
        ),
    ]
